In [1]:
a = 24
print(a)

24


In [2]:
a=24
print("i am" ,a, "years old")

i am 24 years old


In [3]:
a=24
b=25
c=a+b
print(c)

49


In [4]:
a=int(input("enter a"))
b=int(input("enter b"))
c=a/b
print(c)

enter a10
enter b20
0.5


In [5]:
a=int(input("enter a"))
b=int(input("enter b"))
c=a//b
print(c)

enter a10
enter b20
0


In [6]:
a=int(input("enter a"))
b=int(input("enter b"))
c=a%b
print(c)

enter a10
enter b20
10


In [7]:
a=int(input("enter a"))
b=int(input("enter b"))
if(a>b):
    print("a is greater than b ")
else:
    print(" b is greater")

enter a50
enter b120
 b is greater


In [8]:
password="ramya"
pwd=input("enter a password= ")
if(password==pwd):
    print("welcome")
else:
    print("wrong password")

enter a password= ramya
welcome


In [9]:
password="ramya"
pinn=1234
pwd=input("enter a password= ")
pin=int(input("enter pin"))
if(password==pwd and pin==pinn):
    print("welcome")
else:
    print("wrong password try again")

enter a password= 521
enter pin12345
wrong password try again


In [10]:
password="ramya"
pinn=1234
pwd=input("enter a password= ")
pin=int(input("enter pin"))
if(password==pwd or pin==pinn):
    print("welcome")
else:
    print("wrong password try again")

enter a password= 566
enter pin1234
welcome


In [11]:
s="hello how are you?"
print(s[-4:-1])

you


In [12]:
s="hello how are you?"
print(s[0:5])

hello


In [13]:
for i in range(0,5):
    print(s[i])

h
e
l
l
o


In [14]:
fact=1
i=1
while i<=5:
    fact*=i
    i=i+1
print(fact)

120


In [15]:
sum=0
i=0
while i<=6:
    sum+=i
    i=i+1
    print(sum)

0
1
3
6
10
15
21


In [16]:
list1=[9,90,'like',90.1,True,'like']
print(list1)

[9, 90, 'like', 90.1, True, 'like']


In [17]:
list1=[9,90,'like',90.1,True,'like']
print(list1)
list1.append('ramya')
print(list1)
list1.insert(4,'spandana') #insert(index,ele)
print(list1)
list1.remove('like')
print(list1)
list1.pop(5)
print(list1)
list1.clear()
print(list1)

[9, 90, 'like', 90.1, True, 'like']
[9, 90, 'like', 90.1, True, 'like', 'ramya']
[9, 90, 'like', 90.1, 'spandana', True, 'like', 'ramya']
[9, 90, 90.1, 'spandana', True, 'like', 'ramya']
[9, 90, 90.1, 'spandana', True, 'ramya']
[]


In [18]:
list4=[89,45,12,23,99,80]
list4.sort()
list4

[12, 23, 45, 80, 89, 99]

In [19]:
list4=[89,45,12,23,99,80]
list4.sort(reverse=True)
list4

[99, 89, 80, 45, 23, 12]

In [20]:
list5=[89,45,12,23,99,80,76,]
list6=sorted(list5)
list6

[12, 23, 45, 76, 80, 89, 99]

In [21]:
list5=[89,45,12,23,99,80,76]
list5.sort()
for i in list5:
    print(i*i)

144
529
2025
5776
6400
7921
9801


In [22]:
listnew=[i*i for i in list6]
listnew

[144, 529, 2025, 5776, 6400, 7921, 9801]

In [23]:
list6=[99,45,12,103,46]
s=[]
for i in list6:
    if i>50:
        s.append(i*i)
print(s)

[9801, 10609]


In [26]:
slc = [i*i for i in list6 if i>50]

In [27]:
print(slc)

[9801, 10609]


In [ ]:
marks=[50,90,70,80,90,100]
grades=[]
for i  in marks:
    if i>=90:
        grades.append("a")
    else:
        grades.append("b")
grades

In [39]:
#if the salry is > than 50k reduce tax 10% else reduce 5% and save remaining slry in new list

sal=[19000,78000,10000,56000,45000,12000]
final=[]
for i in sal:
    if i>50000:
        tax=i*0.1
        total=i-tax
        final.append(total)
    else:
        tax=i*0.05
        total=i-tax
        final.append(total)
final


[18050.0, 70200.0, 9500.0, 50400.0, 42750.0, 11400.0]

In [44]:
fslc=[i-i*0.1 if i>50000 else i-i*0.05 for i in sal]
fslc

[18050.0, 70200.0, 9500.0, 50400.0, 42750.0, 11400.0]

In [46]:
list2=[90,45,23,12,91]
list4=[89,45,12,23,99]

for i,j in zip(list2,list4):
    print(i+j)
    

179
90
35
35
190


In [47]:
tupl=(34,'hello',90,'hi',90.6)
tupl

(34, 'hello', 90, 'hi', 90.6)

In [48]:
tup2=(90,45,67)
tup3=sorted(tup2)
tup3

[45, 67, 90]

dictionary


In [50]:
dict={1:"joe",2:"veena",3:"hanumanth"}
dict

{1: 'joe', 2: 'veena', 3: 'hanumanth'}

In [53]:
dict2={'name':"ramya",'hobbies': ['sleeping','eating','playing']}
print(dict2['hobbies'])

['sleeping', 'eating', 'playing']


In [55]:
dict2.keys()

dict_keys(['name', 'hobbies'])

In [56]:
dict2.values()


dict_values(['ramya', ['sleeping', 'eating', 'playing']])

In [57]:
dict2.items()

dict_items([('name', 'ramya'), ('hobbies', ['sleeping', 'eating', 'playing'])])

In [61]:
dict2['hobbies'][1]

'eating'

In [63]:
print("ramya hobbies are",dict2['hobbies'])

ramya hobbies are ['sleeping', 'eating', 'playing']


In [65]:
list1=[90,56,90,34,90,56]
s2=set(list1)
s2

{34, 56, 90}

DAY2


In [6]:
import numpy as np
#arrays
ar1=np.array([34,56,23,12])
ar2=np.array([56,78,90,56])
ar1+ar2

array([ 90, 134, 113,  68])

In [8]:
import numpy as np
#arrays
ar1=np.array([34,56,23,12])
ar2=np.array([56,78,90,56])
ar2-ar1

array([22, 22, 67, 44])

In [9]:
#intrinsic creation of array
ar3=np.ones((2,3))
print(ar3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
ar4=np.zeros((4,5))
print(ar4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
ar5=np.eye(5)
print(ar5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
ar6=np.arange(8,1001,8) #start,stop,step
print(ar6)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [19]:
np.ndim(ar4) #dimension of the array

2

In [20]:
np.shape(ar4)

(4, 5)

In [22]:
ar8=np.array([[3,4,5],[1,2,3]])
print(ar8)

[[3 4 5]
 [1 2 3]]


In [24]:
ar9=np.array([[[3,4,5],[1,2,3]],[[3,4,5],[5,6,7]]])
print(ar9)

[[[3 4 5]
  [1 2 3]]

 [[3 4 5]
  [5 6 7]]]


# statistics

In [25]:
m=np.array([70,89,50,79,89,46])

In [27]:
avg=np.mean(m)
print(avg)

med=np.median(m)
print(med)

sd=np.std(m)
print(sd)

70.5
74.5
17.211914478058507


# random

In [28]:
from numpy import random as rd 
#import parent import child as nn

In [30]:
r1=rd.randint(90)
print(r1)

24


In [32]:
r2=rd.randint(90,size=5)
print(r2)

[82 28 13  3 45]


In [34]:
r3=rd.randint(100,size=(4,5))
print(r3)

[[23  7 20 81  1]
 [71 50 70 68 35]
 [ 8 84 25 61 31]
 [68 94 75 34 31]]
